server:
  port: 8080

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/ssm?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  
  redis:
    host: localhost
    port: 6379
    password: 123456
    timeout: 2000
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-wait: 2000ms
          
#  security:
#    oauth2:
#      client:
#        registration:
#          # OAuth2 客户端配置
#          google:
#            client-id: your-client-id
#            client-secret: your-client-secret
#            scope: profile, email
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            authorization-grant-type: authorization_code
#        provider:
#          google:
#            authorization-uri: https://accounts.google.com/o/oauth2/auth
#            token-uri: https://oauth2.googleapis.com/token
#            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
#            user-name-attribute: sub
          
          
          
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

# 配置全局异常处理
errors:
  include-stacktrace: never
  whitelabel:
    enabled: false

# 配置 Swagger
springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html

# 配置 JWT
jwt:
  secret: your_jwt_secret_key
  expiration: 86400 # 24小时过期时间（以秒为单位）
  header: Authorization
  prefix: Bearer

# 配置 CORS（跨域资源共享）
cors:
  allowed-origins: "http://localhost:3000"
  allowed-methods: GET, POST, PUT, DELETE
  allowed-headers: Authorization, Content-Type
  allow-credentials: true

# 配置自定义错误页面
#server:
#  error:
#    whitelabel:
#      enabled: false
#    include-message: always
#    include-binding-errors: always

# 配置缓存
cache:
  type: redis
  redis:
    time-to-live: 60s
    
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.ssm
  configuration:
    map-underscore-to-camel-case: true